In [83]:
import numpy as np

from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [84]:
X, y = load_diabetes(return_X_y = True)

In [85]:
X.shape

(442, 10)

In [86]:
y.shape

(442,)

In [87]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2)

In [88]:
model = LinearRegression()

In [89]:
model.fit(X_train, y_train)

LinearRegression()

In [90]:
model.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [91]:
model.intercept_

np.float64(151.88331005254167)

In [92]:
y_pred = model.predict(X_test)
y_pred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [93]:
r2_score(y_test, y_pred)

0.4399338661568968

In [94]:
import random
class MBGDRegressor:
    def __init__(self, batch_size, learning_rate = 0.01, epochs = 100):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.coef_ = None
        self.intercept_ = None
        self.batch_size = batch_size

    def fit(self, X_train, y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):
            for j in range(int(X_train.shape[0] / self.batch_size)):
                # Ensure batch_size is an integer for random.sample
                index = random.sample(range(X_train.shape[0]), int(self.batch_size))

                y_hat = np.dot(X_train[index], self.coef_) + self.intercept_

                intercept_der = -2 * np.mean(y_train[index] - y_hat)
                self.intercept_ = self.intercept_ - (self.learning_rate * intercept_der)

                # Corrected dot product calculation
                coef_der = -2 * np.dot((y_train[index] - y_hat), X_train[index])
                self.coef_ = self.coef_ - (self.learning_rate * coef_der)

            print(self.intercept_, self.coef_)


    def predict(self, X_test):
        return np.dot(X_test, self.coef_) + self.intercept_

In [95]:
mbr = MBGDRegressor(batch_size = int(X_train.shape[0] / 50), learning_rate = 0.01, epochs = 100)

In [96]:
mbr.fit(X_train, y_train)

98.34574889871635 [ 7.07534278  5.66949315 15.5268996  15.1270591  -0.7743008  -1.04934192
 -9.68218403  8.0733922  13.3314415   8.31260062]
130.85002376630698 [  8.76893483   4.29616152  24.93198323  22.04622728   2.92954714
   1.04241411 -16.78422557  15.5259528   25.90887428  13.7023329 ]
148.2991685632038 [ 14.07332858   6.50321469  41.02861952  33.53750525   7.78488253
   5.14105938 -27.43932145  26.05943456  40.2549698   22.10331014]
144.7484375021666 [ 18.72271439   7.25528666  53.07600348  41.56273864  13.47864203
   9.22708498 -35.43107724  34.54830108  54.42154519  29.16904561]
148.86382323367516 [ 23.15220046   8.70171728  67.44620242  50.66268082  17.52719386
  12.12662421 -45.04526578  44.05642742  68.57501412  38.46224962]
155.88250695269198 [ 25.63741729   9.66455663  77.99396301  59.93220732  19.88354423
  13.06239606 -53.27675708  51.9487205   81.03829721  44.83571377]
153.28766225338023 [ 29.50688127  11.35984636  89.46871882  70.76121046  22.48817565
  14.62463112 -6

In [105]:
mbr.coef_

array([  30.73822671, -137.94987429,  452.9799815 ,  302.99265725,
        -25.04093136,  -99.39613559, -189.16096102,  111.96442945,
        418.65805897,  108.12896539])

In [106]:
mbr.intercept_

np.float64(152.2955039036401)

In [97]:
y_pred = mbr.predict(X_test)
y_pred

array([152.62367952, 196.52595474, 131.76717404, 105.54893763,
       260.85328821, 249.04960733, 111.61123073, 115.56212156,
        95.88821945, 187.28438947, 149.3158265 , 173.2945919 ,
       180.79929668, 140.22421945, 282.33352971,  88.42010657,
       197.42724462, 146.54212063, 134.99768002, 132.46589903,
       144.42863204, 176.21296963, 155.4405637 , 175.9728736 ,
       127.68946499, 221.27277632, 199.26617649, 105.95648786,
        56.96883655, 238.27369968, 241.74227396, 114.5546666 ,
        69.32400089, 100.1965341 , 204.10910529, 164.40444933,
       163.26834712, 193.7673864 , 113.81378709, 237.49314579,
       140.47928438, 123.19831062, 187.3778528 , 186.94977976,
       175.10851656, 144.44330225, 170.85331239, 295.09113442,
       109.4941983 , 175.19700942, 250.38897294, 138.94614399,
       149.31316417, 131.06300269, 191.92839909, 100.03085054,
       136.24590439,  78.50088582, 157.80598567, 152.58087573,
       164.32886453, 164.09773326, 104.4444814 , 221.49

In [99]:
r2_score(y_test, y_pred)

0.4521962143869581

In [100]:
from sklearn.linear_model import SGDRegressor

In [101]:
sgd = SGDRegressor(learning_rate = 'constant', eta0 = 0.1)

In [102]:
batch_size = 35

for i in range(100):
    index = random.sample(range(X_train.shape[0]), batch_size)
    sgd.partial_fit(X_train[index], y_train[index])

In [103]:
sgd.coef_

array([  73.86731255,  -62.43856816,  331.16250339,  239.94978288,
         17.58731787,  -26.49775556, -181.81906442,  137.88286012,
        321.50005738,  137.39833673])

In [104]:
sgd.intercept_

array([153.6101402])

In [107]:
y_pred = sgd.predict(X_test)

In [108]:
r2_score(y_test, y_pred)

0.42893331964289627